title: "ECTester"
description: "Tester of Eliptic curve support on the JavaCard smartcard platform."
theme: jekyll-theme-cayman

markdown: kramdown

exclude:
 - Gemfile
 - Gemfile.lock

collections:
  results:
    output: true

defaults:
 - scope:
     path: ""
     type: results
   values:
     layout: result_page
     permalink: /:collection/:path/