title: "ECTester"
description: "Tests support and behavior of elliptic curve cryptography implementations on JavaCards (TYPE_EC_FP and TYPE_EC_F2M) and on selected software libraries."
repository: crocs-muni/ECTester
theme: jekyll-theme-cayman

markdown: kramdown

exclude:
 - Gemfile
 - Gemfile.lock

collections:
  results:
    output: true
  performance:
    output: true

defaults:
 - scope:
     path: ""
   values:
     layout: "default"
 - scope:
     path: ""
     type: "results"
   values:
     permalink: /:collection/:path/
 - scope:
     path: "_results/default"
     type: "results"
   values:
     layout: default_suite
     category: Default
 - scope:
     path: "_results/wrong"
     type: "results"
   values:
     layout: wrong_suite
     category: Wrong
 - scope:
     path: "_results/invalid"
     type: "results"
   values:
     layout: invalid_suite
     category: Invalid
 - scope:
     path: "_results/composite"
     type: "results"
   values:
     layout: composite_suite
     category: Composite
 - scope:
     path: "_results/twist"
     type: "results"
   values:
     layout: twist_suite
     category: Twist
 - scope:
     path: "_results/wrong"
     type: "results"
   values:
     layout: wrong_suite
     category: Wrong
 - scope:
     path: "_results/cofactor"
     type: "results"
   values:
     layout: cofactor_suite
     category: Cofactor
 - scope:
     path: "_results/test-vectors"
     type: "results"
   values:
     layout: test_vectors_suite
     category: "Test vectors"
 - scope:
     path: ""
     type: "performance"
   values:
     permalink: /:collection/:path/
 - scope:
     path: "_performance/ecdh"
     type: "performance"
   values:
     layout: ecdh_performance
     category: "ECDH performance"
 - scope:
     path: "_performance/ecdsa"
     type: "performance"
   values:
     layout: ecdsa_performance
     category: "ECDSA performance"
 - scope:
     path: "_performance/keygen"
     type: "performance"
   values:
     layout: keygen_performance
     category: "Key generation performance"